-- =========================
-- DROP (ambiente de dev)
-- =========================
DROP TABLE IF EXISTS tb_user_role;
DROP TABLE IF EXISTS tb_text_part_progress;
DROP TABLE IF EXISTS tb_text_part;
DROP TABLE IF EXISTS tb_text;
DROP TABLE IF EXISTS tb_role;
DROP TABLE IF EXISTS tb_user;

-- =========================
-- CREATE TABLES
-- =========================
CREATE TABLE tb_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    authority VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE tb_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR(255) UNIQUE,
    last_name VARCHAR(255),
    name VARCHAR(255),
    password VARCHAR(255),
    phone VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE tb_text (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    completed BOOLEAN,
    moment TIMESTAMP WITHOUT TIME ZONE,
    user_id BIGINT,
    module VARCHAR(255),
    title VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE tb_text_part (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    part_number INTEGER,
    text_id BIGINT,
    audio_path VARCHAR(255),
    content VARCHAR(255),
    PRIMARY KEY (id),
    UNIQUE (part_number, text_id)
);

CREATE TABLE tb_text_part_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    complet BOOLEAN,
    d1_final_check INTEGER,
    d1_listen_only INTEGER,
    d1_read_listen INTEGER,
    d2_final_check INTEGER,
    d2_listen_only INTEGER,
    d2_read_listen INTEGER,
    last_activity_at TIMESTAMP,
    text_part_id BIGINT,
    user_id BIGINT,
    PRIMARY KEY (id)
);

CREATE TABLE tb_user_role (
    role_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, user_id)
);

-- =========================
-- FOREIGN KEYS
-- =========================
ALTER TABLE tb_text
    ADD CONSTRAINT fk_text_user FOREIGN KEY (user_id) REFERENCES tb_user;

ALTER TABLE tb_text_part
    ADD CONSTRAINT fk_text_part_text FOREIGN KEY (text_id) REFERENCES tb_text;

ALTER TABLE tb_text_part_progress
    ADD CONSTRAINT fk_progress_text_part FOREIGN KEY (text_part_id) REFERENCES tb_text_part;

ALTER TABLE tb_text_part_progress
    ADD CONSTRAINT fk_progress_user FOREIGN KEY (user_id) REFERENCES tb_user;

ALTER TABLE tb_user_role
    ADD CONSTRAINT fk_user_role_role FOREIGN KEY (role_id) REFERENCES tb_role;

ALTER TABLE tb_user_role
    ADD CONSTRAINT fk_user_role_user FOREIGN KEY (user_id) REFERENCES tb_user;

-- =========================
-- INSERTS
-- =========================
INSERT INTO tb_user (name, email, password)
VALUES 
('Admin User', 'admin@example.com', '$2a$10$w9y9yAyQ1j9TBKE19RpVZ.6V3k7h.cYl5xHibIe0ZL57e1tUZW.A6'),
('Maria', 'maria@example.com', '$2a$10$w9y9yAyQ1j9TBKE19RpVZ.6V3k7h.cYl5xHibIe0ZL57e1tUZW.A6');

INSERT INTO tb_role (authority)
VALUES 
('ROLE_OPERATOR'),
('ROLE_ADMIN');

INSERT INTO tb_user_role (user_id, role_id)
VALUES 
(1, 1),
(1, 2),
(2, 1);

INSERT INTO tb_text (completed, moment, user_id, module, title)
VALUES 
(false, CURRENT_TIMESTAMP, 1, 'Módulo 1', 'My Lord Bag of Rice');

INSERT INTO tb_text_part (part_number, text_id, content, audio_path)
VALUES
(1, 1, 'Long, long ago there lived in Japan a brave warrior known to all as Tawara Toda...', 'audios/full_intro.mp3'),
(2, 1, 'He had not gone far when he came to the bridge...', 'audios/full_intro.mp3'),
(3, 1, 'He was a brave man, however...', 'audios/full_intro.mp3');

INSERT INTO tb_text_part_progress 
(d1_read_listen, d1_listen_only, d1_final_check, d2_read_listen, d2_listen_only, d2_final_check, text_part_id, user_id, last_activity_at, complet)
VALUES
(20, 20, 20, 20, 20, 20, 1, 1, CURRENT_TIMESTAMP, true),
(20, 20, 20, 20, 10, 0, 2, 1, CURRENT_TIMESTAMP, false),
(15, 0, 0, 0, 0, 0, 3, 1, CURRENT_TIMESTAMP, false);