spring.application.name=repetilingua

spring.profiles.active=${APP_PROFILE}
spring.jpa.open-in-view=false

# Valores de Configuracao
# Mapeamento do Client ID e Secret para o Spring Security / OAuth2 / JWT
security.client-id=${SECURITY_CLIENT_ID:repetilingua}
security.client-secret=${SECURITY_CLIENT_SECRET:repetilingua-secret}
security.jwt.token.secret-key=${JWT_SECRET:chave_secreta_jwt_padrao_repetilingua_123456}

cors.origins=${CORS_ORIGINS}