spring.application.name=repetilingua

spring.profiles.active=${APP_PROFILE}
spring.jpa.open-in-view=false

# Valores de Configuracao
security.client-id=${CLIENT_ID}
security.client-secret=${CLIENT_SECRET}
security.jwt.duration=${JWT_DURATION}

cors.origins=${CORS_ORIGINS}